# Generated by Django 5.0.14 on 2026-02-05 00:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('triassic', 'Triassic'), ('jurassic', 'Jurassic'), ('cretaceous', 'Cretaceous')], max_length=100, unique=True)),
                ('era', models.CharField(choices=[('mesozoic', 'Mesozoic')], default='mesozoic', max_length=100)),
                ('start_mya', models.IntegerField(help_text='Million years ago (start)')),
                ('end_mya', models.IntegerField(help_text='Million years ago (end)')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_mya'],
            },
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('puzzleaurus', 'Puzzleaurus'), ('memodyn', 'Memodyn')], max_length=20)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('diet', models.CharField(choices=[('herbivore', 'Herbivore'), ('carnivore', 'Carnivore'), ('omnivore', 'Omnivore')], max_length=20)),
                ('length_meters', models.DecimalField(decimal_places=2, help_text='Length in meters', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('description', models.TextField()),
                ('fun_fact', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dinosaurs/')),
                ('discovered_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='encyclopedia.period')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('tokens', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collected', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_items', to=settings.AUTH_USER_MODEL)),
                ('dinosaur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.dinosaur')),
            ],
            options={
                'ordering': ['dinosaur__period', 'dinosaur__name'],
                'unique_together': {('user', 'dinosaur')},
            },
        ),
    ]
